<?php
/**
 * LeadQuoteLoanResource
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ageras\Api
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ageras.com API
 *
 * this is the Ageras API
 *
 * OpenAPI spec version: 2.0
 * Contact: cto@ageras.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Ageras\Api;

use \ArrayAccess;

/**
 * LeadQuoteLoanResource Class Doc Comment
 *
 * @category    Class
 * @package     Ageras\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LeadQuoteLoanResource implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'LeadQuoteLoanResource';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'title' => 'string',
        'loan_amount_excl_vat' => '\Ageras\Api\AmountResource',
        'duration_months' => 'int',
        'apr_interest_rate' => 'float',
        'total_loan_amount_excl_vat' => '\Ageras\Api\AmountResource'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'title' => 'title',
        'loan_amount_excl_vat' => 'loan_amount_excl_vat',
        'duration_months' => 'duration_months',
        'apr_interest_rate' => 'apr_interest_rate',
        'total_loan_amount_excl_vat' => 'total_loan_amount_excl_vat'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'title' => 'setTitle',
        'loan_amount_excl_vat' => 'setLoanAmountExclVat',
        'duration_months' => 'setDurationMonths',
        'apr_interest_rate' => 'setAprInterestRate',
        'total_loan_amount_excl_vat' => 'setTotalLoanAmountExclVat'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'title' => 'getTitle',
        'loan_amount_excl_vat' => 'getLoanAmountExclVat',
        'duration_months' => 'getDurationMonths',
        'apr_interest_rate' => 'getAprInterestRate',
        'total_loan_amount_excl_vat' => 'getTotalLoanAmountExclVat'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['loan_amount_excl_vat'] = isset($data['loan_amount_excl_vat']) ? $data['loan_amount_excl_vat'] : null;
        $this->container['duration_months'] = isset($data['duration_months']) ? $data['duration_months'] : null;
        $this->container['apr_interest_rate'] = isset($data['apr_interest_rate']) ? $data['apr_interest_rate'] : null;
        $this->container['total_loan_amount_excl_vat'] = isset($data['total_loan_amount_excl_vat']) ? $data['total_loan_amount_excl_vat'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param int $id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets title
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     * @param string $title
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets loan_amount_excl_vat
     * @return \Ageras\Api\AmountResource
     */
    public function getLoanAmountExclVat()
    {
        return $this->container['loan_amount_excl_vat'];
    }

    /**
     * Sets loan_amount_excl_vat
     * @param \Ageras\Api\AmountResource $loan_amount_excl_vat
     * @return $this
     */
    public function setLoanAmountExclVat($loan_amount_excl_vat)
    {
        $this->container['loan_amount_excl_vat'] = $loan_amount_excl_vat;

        return $this;
    }

    /**
     * Gets duration_months
     * @return int
     */
    public function getDurationMonths()
    {
        return $this->container['duration_months'];
    }

    /**
     * Sets duration_months
     * @param int $duration_months
     * @return $this
     */
    public function setDurationMonths($duration_months)
    {
        $this->container['duration_months'] = $duration_months;

        return $this;
    }

    /**
     * Gets apr_interest_rate
     * @return float
     */
    public function getAprInterestRate()
    {
        return $this->container['apr_interest_rate'];
    }

    /**
     * Sets apr_interest_rate
     * @param float $apr_interest_rate
     * @return $this
     */
    public function setAprInterestRate($apr_interest_rate)
    {
        $this->container['apr_interest_rate'] = $apr_interest_rate;

        return $this;
    }

    /**
     * Gets total_loan_amount_excl_vat
     * @return \Ageras\Api\AmountResource
     */
    public function getTotalLoanAmountExclVat()
    {
        return $this->container['total_loan_amount_excl_vat'];
    }

    /**
     * Sets total_loan_amount_excl_vat
     * @param \Ageras\Api\AmountResource $total_loan_amount_excl_vat
     * @return $this
     */
    public function setTotalLoanAmountExclVat($total_loan_amount_excl_vat)
    {
        $this->container['total_loan_amount_excl_vat'] = $total_loan_amount_excl_vat;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Ageras\Api\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Ageras\Api\ObjectSerializer::sanitizeForSerialization($this));
    }
}


