<?php
/**
 * RevenueSegmentResource
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ageras\Api
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ageras.com API
 *
 * this is the Ageras API
 *
 * OpenAPI spec version: 2.0
 * Contact: cto@ageras.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Ageras\Api;

use \ArrayAccess;

/**
 * RevenueSegmentResource Class Doc Comment
 *
 * @category    Class
 * @package     Ageras\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RevenueSegmentResource implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'RevenueSegmentResource';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'geo_code' => 'string',
        'display_name' => 'string',
        'minimum_revenue' => '\Ageras\Api\AmountResource',
        'maximum_revenue' => '\Ageras\Api\AmountResource',
        'lb_price_excl_vat' => '\Ageras\Api\AmountResource',
        'pps_price_excl_vat' => '\Ageras\Api\AmountResource',
        'minimum_lb_price_excl_vat' => '\Ageras\Api\AmountResource',
        'minimum_pps_price_excl_vat' => '\Ageras\Api\AmountResource',
        'lead_category' => '\Ageras\Api\LeadCategoryResource',
        'archived_at' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'geo_code' => 'geo_code',
        'display_name' => 'display_name',
        'minimum_revenue' => 'minimum_revenue',
        'maximum_revenue' => 'maximum_revenue',
        'lb_price_excl_vat' => 'lb_price_excl_vat',
        'pps_price_excl_vat' => 'pps_price_excl_vat',
        'minimum_lb_price_excl_vat' => 'minimum_lb_price_excl_vat',
        'minimum_pps_price_excl_vat' => 'minimum_pps_price_excl_vat',
        'lead_category' => 'lead_category',
        'archived_at' => 'archived_at'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'geo_code' => 'setGeoCode',
        'display_name' => 'setDisplayName',
        'minimum_revenue' => 'setMinimumRevenue',
        'maximum_revenue' => 'setMaximumRevenue',
        'lb_price_excl_vat' => 'setLbPriceExclVat',
        'pps_price_excl_vat' => 'setPpsPriceExclVat',
        'minimum_lb_price_excl_vat' => 'setMinimumLbPriceExclVat',
        'minimum_pps_price_excl_vat' => 'setMinimumPpsPriceExclVat',
        'lead_category' => 'setLeadCategory',
        'archived_at' => 'setArchivedAt'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'geo_code' => 'getGeoCode',
        'display_name' => 'getDisplayName',
        'minimum_revenue' => 'getMinimumRevenue',
        'maximum_revenue' => 'getMaximumRevenue',
        'lb_price_excl_vat' => 'getLbPriceExclVat',
        'pps_price_excl_vat' => 'getPpsPriceExclVat',
        'minimum_lb_price_excl_vat' => 'getMinimumLbPriceExclVat',
        'minimum_pps_price_excl_vat' => 'getMinimumPpsPriceExclVat',
        'lead_category' => 'getLeadCategory',
        'archived_at' => 'getArchivedAt'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['geo_code'] = isset($data['geo_code']) ? $data['geo_code'] : null;
        $this->container['display_name'] = isset($data['display_name']) ? $data['display_name'] : null;
        $this->container['minimum_revenue'] = isset($data['minimum_revenue']) ? $data['minimum_revenue'] : null;
        $this->container['maximum_revenue'] = isset($data['maximum_revenue']) ? $data['maximum_revenue'] : null;
        $this->container['lb_price_excl_vat'] = isset($data['lb_price_excl_vat']) ? $data['lb_price_excl_vat'] : null;
        $this->container['pps_price_excl_vat'] = isset($data['pps_price_excl_vat']) ? $data['pps_price_excl_vat'] : null;
        $this->container['minimum_lb_price_excl_vat'] = isset($data['minimum_lb_price_excl_vat']) ? $data['minimum_lb_price_excl_vat'] : null;
        $this->container['minimum_pps_price_excl_vat'] = isset($data['minimum_pps_price_excl_vat']) ? $data['minimum_pps_price_excl_vat'] : null;
        $this->container['lead_category'] = isset($data['lead_category']) ? $data['lead_category'] : null;
        $this->container['archived_at'] = isset($data['archived_at']) ? $data['archived_at'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param int $id Primary ID.
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets geo_code
     * @return string
     */
    public function getGeoCode()
    {
        return $this->container['geo_code'];
    }

    /**
     * Sets geo_code
     * @param string $geo_code Geo code.
     * @return $this
     */
    public function setGeoCode($geo_code)
    {
        $this->container['geo_code'] = $geo_code;

        return $this;
    }

    /**
     * Gets display_name
     * @return string
     */
    public function getDisplayName()
    {
        return $this->container['display_name'];
    }

    /**
     * Sets display_name
     * @param string $display_name Human-readable name.
     * @return $this
     */
    public function setDisplayName($display_name)
    {
        $this->container['display_name'] = $display_name;

        return $this;
    }

    /**
     * Gets minimum_revenue
     * @return \Ageras\Api\AmountResource
     */
    public function getMinimumRevenue()
    {
        return $this->container['minimum_revenue'];
    }

    /**
     * Sets minimum_revenue
     * @param \Ageras\Api\AmountResource $minimum_revenue
     * @return $this
     */
    public function setMinimumRevenue($minimum_revenue)
    {
        $this->container['minimum_revenue'] = $minimum_revenue;

        return $this;
    }

    /**
     * Gets maximum_revenue
     * @return \Ageras\Api\AmountResource
     */
    public function getMaximumRevenue()
    {
        return $this->container['maximum_revenue'];
    }

    /**
     * Sets maximum_revenue
     * @param \Ageras\Api\AmountResource $maximum_revenue
     * @return $this
     */
    public function setMaximumRevenue($maximum_revenue)
    {
        $this->container['maximum_revenue'] = $maximum_revenue;

        return $this;
    }

    /**
     * Gets lb_price_excl_vat
     * @return \Ageras\Api\AmountResource
     */
    public function getLbPriceExclVat()
    {
        return $this->container['lb_price_excl_vat'];
    }

    /**
     * Sets lb_price_excl_vat
     * @param \Ageras\Api\AmountResource $lb_price_excl_vat
     * @return $this
     */
    public function setLbPriceExclVat($lb_price_excl_vat)
    {
        $this->container['lb_price_excl_vat'] = $lb_price_excl_vat;

        return $this;
    }

    /**
     * Gets pps_price_excl_vat
     * @return \Ageras\Api\AmountResource
     */
    public function getPpsPriceExclVat()
    {
        return $this->container['pps_price_excl_vat'];
    }

    /**
     * Sets pps_price_excl_vat
     * @param \Ageras\Api\AmountResource $pps_price_excl_vat
     * @return $this
     */
    public function setPpsPriceExclVat($pps_price_excl_vat)
    {
        $this->container['pps_price_excl_vat'] = $pps_price_excl_vat;

        return $this;
    }

    /**
     * Gets minimum_lb_price_excl_vat
     * @return \Ageras\Api\AmountResource
     */
    public function getMinimumLbPriceExclVat()
    {
        return $this->container['minimum_lb_price_excl_vat'];
    }

    /**
     * Sets minimum_lb_price_excl_vat
     * @param \Ageras\Api\AmountResource $minimum_lb_price_excl_vat
     * @return $this
     */
    public function setMinimumLbPriceExclVat($minimum_lb_price_excl_vat)
    {
        $this->container['minimum_lb_price_excl_vat'] = $minimum_lb_price_excl_vat;

        return $this;
    }

    /**
     * Gets minimum_pps_price_excl_vat
     * @return \Ageras\Api\AmountResource
     */
    public function getMinimumPpsPriceExclVat()
    {
        return $this->container['minimum_pps_price_excl_vat'];
    }

    /**
     * Sets minimum_pps_price_excl_vat
     * @param \Ageras\Api\AmountResource $minimum_pps_price_excl_vat
     * @return $this
     */
    public function setMinimumPpsPriceExclVat($minimum_pps_price_excl_vat)
    {
        $this->container['minimum_pps_price_excl_vat'] = $minimum_pps_price_excl_vat;

        return $this;
    }

    /**
     * Gets lead_category
     * @return \Ageras\Api\LeadCategoryResource
     */
    public function getLeadCategory()
    {
        return $this->container['lead_category'];
    }

    /**
     * Sets lead_category
     * @param \Ageras\Api\LeadCategoryResource $lead_category
     * @return $this
     */
    public function setLeadCategory($lead_category)
    {
        $this->container['lead_category'] = $lead_category;

        return $this;
    }

    /**
     * Gets archived_at
     * @return string
     */
    public function getArchivedAt()
    {
        return $this->container['archived_at'];
    }

    /**
     * Sets archived_at
     * @param string $archived_at If and when was the segment archived.
     * @return $this
     */
    public function setArchivedAt($archived_at)
    {
        $this->container['archived_at'] = $archived_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Ageras\Api\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Ageras\Api\ObjectSerializer::sanitizeForSerialization($this));
    }
}


