<?php
/**
 * SoftConversionResourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ageras\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ageras.com API
 *
 * this is the Ageras API
 *
 * OpenAPI spec version: 2.0
 * Contact: cto@ageras.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ageras\Api;

/**
 * SoftConversionResourceTest Class Doc Comment
 *
 * @category    Class */
// * @description SoftConversionResource
/**
 * @package     Ageras\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SoftConversionResourceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SoftConversionResource"
     */
    public function testSoftConversionResource()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {

    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {

    }

    /**
     * Test attribute "subscribed_at"
     */
    public function testPropertySubscribedAt()
    {

    }

    /**
     * Test attribute "full_name"
     */
    public function testPropertyFullName()
    {

    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {

    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {

    }

    /**
     * Test attribute "medium"
     */
    public function testPropertyMedium()
    {

    }

    /**
     * Test attribute "campaign_id"
     */
    public function testPropertyCampaignId()
    {

    }

    /**
     * Test attribute "original_referrer"
     */
    public function testPropertyOriginalReferrer()
    {

    }

    /**
     * Test attribute "conversion_page"
     */
    public function testPropertyConversionPage()
    {

    }

}
