<?php
/**
 * ClientSignUpResourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ageras\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ageras.com API
 *
 * this is the Ageras API
 *
 * OpenAPI spec version: 2.0
 * Contact: cto@ageras.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ageras\Api;

/**
 * ClientSignUpResourceTest Class Doc Comment
 *
 * @category    Class */
// * @description ClientSignUpResource
/**
 * @package     Ageras\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ClientSignUpResourceTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ClientSignUpResource"
     */
    public function testClientSignUpResource()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {

    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {

    }

    /**
     * Test attribute "phone_number"
     */
    public function testPropertyPhoneNumber()
    {

    }

    /**
     * Test attribute "geo_code"
     */
    public function testPropertyGeoCode()
    {

    }

    /**
     * Test attribute "signup_token"
     */
    public function testPropertySignupToken()
    {

    }

    /**
     * Test attribute "expires_at"
     */
    public function testPropertyExpiresAt()
    {

    }

    /**
     * Test attribute "processed_at"
     */
    public function testPropertyProcessedAt()
    {

    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "is_already_created"
     */
    public function testPropertyIsAlreadyCreated()
    {

    }

}
