<?php
/**
 * ContactArchiveResourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ageras\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ageras.com API
 *
 * this is the Ageras API
 *
 * OpenAPI spec version: 2.0
 * Contact: cto@ageras.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ageras\Api;

/**
 * ContactArchiveResourceTest Class Doc Comment
 *
 * @category    Class */
// * @description ContactArchiveResource
/**
 * @package     Ageras\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContactArchiveResourceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ContactArchiveResource"
     */
    public function testContactArchiveResource()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {

    }

    /**
     * Test attribute "sent_at"
     */
    public function testPropertySentAt()
    {

    }

    /**
     * Test attribute "geo_code"
     */
    public function testPropertyGeoCode()
    {

    }

    /**
     * Test attribute "channels"
     */
    public function testPropertyChannels()
    {

    }

    /**
     * Test attribute "lang"
     */
    public function testPropertyLang()
    {

    }

    /**
     * Test attribute "employee"
     */
    public function testPropertyEmployee()
    {

    }

    /**
     * Test attribute "lead"
     */
    public function testPropertyLead()
    {

    }

    /**
     * Test attribute "partner_user"
     */
    public function testPropertyPartnerUser()
    {

    }

}
