<?php
/**
 * KPIPartnersResourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ageras\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ageras.com API
 *
 * this is the Ageras API
 *
 * OpenAPI spec version: 2.0
 * Contact: cto@ageras.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ageras\Api;

/**
 * KPIPartnersResourceTest Class Doc Comment
 *
 * @category    Class */
// * @description KPIPartnersResource
/**
 * @package     Ageras\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class KPIPartnersResourceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "KPIPartnersResource"
     */
    public function testKPIPartnersResource()
    {

    }

    /**
     * Test attribute "avg_credits_used"
     */
    public function testPropertyAvgCreditsUsed()
    {

    }

    /**
     * Test attribute "calls"
     */
    public function testPropertyCalls()
    {

    }

    /**
     * Test attribute "churn"
     */
    public function testPropertyChurn()
    {

    }

    /**
     * Test attribute "refills"
     */
    public function testPropertyRefills()
    {

    }

    /**
     * Test attribute "new_sales"
     */
    public function testPropertyNewSales()
    {

    }

    /**
     * Test attribute "cancellations"
     */
    public function testPropertyCancellations()
    {

    }

    /**
     * Test attribute "satisfactions"
     */
    public function testPropertySatisfactions()
    {

    }

    /**
     * Test attribute "success_ratio"
     */
    public function testPropertySuccessRatio()
    {

    }

    /**
     * Test attribute "unique_spending"
     */
    public function testPropertyUniqueSpending()
    {

    }

    /**
     * Test attribute "active_partner_packages"
     */
    public function testPropertyActivePartnerPackages()
    {

    }

}
