<?php
/**
 * OrderLineResourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ageras\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ageras.com API
 *
 * this is the Ageras API
 *
 * OpenAPI spec version: 2.0
 * Contact: cto@ageras.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ageras\Api;

/**
 * OrderLineResourceTest Class Doc Comment
 *
 * @category    Class */
// * @description OrderLineResource
/**
 * @package     Ageras\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderLineResourceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "OrderLineResource"
     */
    public function testOrderLineResource()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "item"
     */
    public function testPropertyItem()
    {

    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "item_vat_percent"
     */
    public function testPropertyItemVatPercent()
    {

    }

    /**
     * Test attribute "item_vat_amount"
     */
    public function testPropertyItemVatAmount()
    {

    }

    /**
     * Test attribute "item_price_incl_vat"
     */
    public function testPropertyItemPriceInclVat()
    {

    }

    /**
     * Test attribute "item_price_excl_vat"
     */
    public function testPropertyItemPriceExclVat()
    {

    }

    /**
     * Test attribute "vat_amount"
     */
    public function testPropertyVatAmount()
    {

    }

    /**
     * Test attribute "price_incl_vat"
     */
    public function testPropertyPriceInclVat()
    {

    }

    /**
     * Test attribute "price_excl_vat"
     */
    public function testPropertyPriceExclVat()
    {

    }

    /**
     * Test attribute "seller"
     */
    public function testPropertySeller()
    {

    }

}
