<?php
/**
 * PartnerVerificationEntryResourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ageras\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ageras.com API
 *
 * this is the Ageras API
 *
 * OpenAPI spec version: 2.0
 * Contact: cto@ageras.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ageras\Api;

/**
 * PartnerVerificationEntryResourceTest Class Doc Comment
 *
 * @category    Class */
// * @description PartnerVerificationEntryResource
/**
 * @package     Ageras\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PartnerVerificationEntryResourceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "PartnerVerificationEntryResource"
     */
    public function testPartnerVerificationEntryResource()
    {

    }

    /**
     * Test attribute "identifier"
     */
    public function testPropertyIdentifier()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "blocking"
     */
    public function testPropertyBlocking()
    {

    }

    /**
     * Test attribute "requested_by"
     */
    public function testPropertyRequestedBy()
    {

    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {

    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {

    }

}
