<?php
/**
 * PartnerDiscountResourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ageras\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ageras.com API
 *
 * this is the Ageras API
 *
 * OpenAPI spec version: 2.0
 * Contact: cto@ageras.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ageras\Api;

/**
 * PartnerDiscountResourceTest Class Doc Comment
 *
 * @category    Class */
// * @description PartnerDiscountResource
/**
 * @package     Ageras\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PartnerDiscountResourceTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "PartnerDiscountResource"
     */
    public function testPartnerDiscountResource()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "partner_id"
     */
    public function testPropertyPartnerId()
    {

    }

    /**
     * Test attribute "employee_id"
     */
    public function testPropertyEmployeeId()
    {

    }

    /**
     * Test attribute "partner_package_type_id"
     */
    public function testPropertyPartnerPackageTypeId()
    {

    }

    /**
     * Test attribute "discount"
     */
    public function testPropertyDiscount()
    {

    }

    /**
     * Test attribute "starts_at"
     */
    public function testPropertyStartsAt()
    {

    }

    /**
     * Test attribute "ends_at"
     */
    public function testPropertyEndsAt()
    {

    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {

    }

}
