<?php
/**
 * PartnerUserCvAwardResourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ageras\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ageras.com API
 *
 * this is the Ageras API
 *
 * OpenAPI spec version: 2.0
 * Contact: cto@ageras.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ageras\Api;

/**
 * PartnerUserCvAwardResourceTest Class Doc Comment
 *
 * @category    Class */
// * @description PartnerUserCvAwardResource
/**
 * @package     Ageras\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PartnerUserCvAwardResourceTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "PartnerUserCvAwardResource"
     */
    public function testPartnerUserCvAwardResource()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "award_name"
     */
    public function testPropertyAwardName()
    {

    }

    /**
     * Test attribute "issuer"
     */
    public function testPropertyIssuer()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "award_type"
     */
    public function testPropertyAwardType()
    {

    }

    /**
     * Test attribute "reward_date"
     */
    public function testPropertyRewardDate()
    {

    }

    /**
     * Test attribute "validation"
     */
    public function testPropertyValidation()
    {

    }

}
