<?php
/**
 * RecipientResourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ageras\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ageras.com API
 *
 * this is the Ageras API
 *
 * OpenAPI spec version: 2.0
 * Contact: cto@ageras.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ageras\Api;

/**
 * RecipientResourceTest Class Doc Comment
 *
 * @category    Class */
// * @description RecipientResource
/**
 * @package     Ageras\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RecipientResourceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RecipientResource"
     */
    public function testRecipientResource()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "employee_id"
     */
    public function testPropertyEmployeeId()
    {

    }

    /**
     * Test attribute "lead_id"
     */
    public function testPropertyLeadId()
    {

    }

    /**
     * Test attribute "partner_user_id"
     */
    public function testPropertyPartnerUserId()
    {

    }

    /**
     * Test attribute "read_at"
     */
    public function testPropertyReadAt()
    {

    }

    /**
     * Test attribute "hidden_at"
     */
    public function testPropertyHiddenAt()
    {

    }

}
