<?php
/**
 * PartnersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Ageras\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ageras.com API
 *
 * this is the Ageras API
 *
 * OpenAPI spec version: 2.0
 * Contact: cto@ageras.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Ageras\Api;

use \Ageras\Api\Configuration;
use \Ageras\Api\ApiClient;
use \Ageras\Api\ApiException;
use \Ageras\Api\ObjectSerializer;

/**
 * PartnersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ageras\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PartnersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for partnersActionsCreate
     *
     * .
     *
     */
    public function testPartnersActionsCreate()
    {

    }

    /**
     * Test case for partnersAggregationsIndex
     *
     * .
     *
     */
    public function testPartnersAggregationsIndex()
    {

    }

    /**
     * Test case for partnersAllocationdeliveriesIndex
     *
     * .
     *
     */
    public function testPartnersAllocationdeliveriesIndex()
    {

    }

    /**
     * Test case for partnersAllocationdeliveriesIndex_0
     *
     * .
     *
     */
    public function testPartnersAllocationdeliveriesIndex0()
    {

    }

    /**
     * Test case for partnersAllocationpausesCreate
     *
     * .
     *
     */
    public function testPartnersAllocationpausesCreate()
    {

    }

    /**
     * Test case for partnersAssigneesCreate
     *
     * .
     *
     */
    public function testPartnersAssigneesCreate()
    {

    }

    /**
     * Test case for partnersAssigneesDelete
     *
     * .
     *
     */
    public function testPartnersAssigneesDelete()
    {

    }

    /**
     * Test case for partnersAssigneesIndex
     *
     * .
     *
     */
    public function testPartnersAssigneesIndex()
    {

    }

    /**
     * Test case for partnersBankaccountsCreate
     *
     * .
     *
     */
    public function testPartnersBankaccountsCreate()
    {

    }

    /**
     * Test case for partnersBankaccountsIndex
     *
     * .
     *
     */
    public function testPartnersBankaccountsIndex()
    {

    }

    /**
     * Test case for partnersBrowserpushsubscriptionsCreate
     *
     * .
     *
     */
    public function testPartnersBrowserpushsubscriptionsCreate()
    {

    }

    /**
     * Test case for partnersBusinessunitcontractsCreate
     *
     * .
     *
     */
    public function testPartnersBusinessunitcontractsCreate()
    {

    }

    /**
     * Test case for partnersBusinessunitcontractsGet
     *
     * .
     *
     */
    public function testPartnersBusinessunitcontractsGet()
    {

    }

    /**
     * Test case for partnersBusinessunitcontractsIndex
     *
     * .
     *
     */
    public function testPartnersBusinessunitcontractsIndex()
    {

    }

    /**
     * Test case for partnersBusinessunitsAllocationlimitsCreate
     *
     * .
     *
     */
    public function testPartnersBusinessunitsAllocationlimitsCreate()
    {

    }

    /**
     * Test case for partnersBusinessunitsAllocationlimitsDelete
     *
     * .
     *
     */
    public function testPartnersBusinessunitsAllocationlimitsDelete()
    {

    }

    /**
     * Test case for partnersBusinessunitsAllocationlimitsIndex
     *
     * .
     *
     */
    public function testPartnersBusinessunitsAllocationlimitsIndex()
    {

    }

    /**
     * Test case for partnersBusinessunitsAllocationlimitsUpdate
     *
     * .
     *
     */
    public function testPartnersBusinessunitsAllocationlimitsUpdate()
    {

    }

    /**
     * Test case for partnersBusinessunitsAllocationquotasCreate
     *
     * .
     *
     */
    public function testPartnersBusinessunitsAllocationquotasCreate()
    {

    }

    /**
     * Test case for partnersBusinessunitsAllocationquotasDelete
     *
     * .
     *
     */
    public function testPartnersBusinessunitsAllocationquotasDelete()
    {

    }

    /**
     * Test case for partnersBusinessunitsAllocationquotasIndex
     *
     * .
     *
     */
    public function testPartnersBusinessunitsAllocationquotasIndex()
    {

    }

    /**
     * Test case for partnersBusinessunitsCreate
     *
     * .
     *
     */
    public function testPartnersBusinessunitsCreate()
    {

    }

    /**
     * Test case for partnersBusinessunitsDelete
     *
     * .
     *
     */
    public function testPartnersBusinessunitsDelete()
    {

    }

    /**
     * Test case for partnersBusinessunitsGet
     *
     * .
     *
     */
    public function testPartnersBusinessunitsGet()
    {

    }

    /**
     * Test case for partnersBusinessunitsIndex
     *
     * .
     *
     */
    public function testPartnersBusinessunitsIndex()
    {

    }

    /**
     * Test case for partnersBusinessunitsIndustriesIndex
     *
     * .
     *
     */
    public function testPartnersBusinessunitsIndustriesIndex()
    {

    }

    /**
     * Test case for partnersBusinessunitsIndustriesUpdate
     *
     * .
     *
     */
    public function testPartnersBusinessunitsIndustriesUpdate()
    {

    }

    /**
     * Test case for partnersBusinessunitsRevenuerangesCreate
     *
     * .
     *
     */
    public function testPartnersBusinessunitsRevenuerangesCreate()
    {

    }

    /**
     * Test case for partnersBusinessunitsSectorsIndex
     *
     * .
     *
     */
    public function testPartnersBusinessunitsSectorsIndex()
    {

    }

    /**
     * Test case for partnersBusinessunitsSectorsUpdate
     *
     * .
     *
     */
    public function testPartnersBusinessunitsSectorsUpdate()
    {

    }

    /**
     * Test case for partnersBusinessunitsSegmentationgeoregionsIndex
     *
     * .
     *
     */
    public function testPartnersBusinessunitsSegmentationgeoregionsIndex()
    {

    }

    /**
     * Test case for partnersBusinessunitsSegmentationgeoregionsUpdate
     *
     * .
     *
     */
    public function testPartnersBusinessunitsSegmentationgeoregionsUpdate()
    {

    }

    /**
     * Test case for partnersBusinessunitsTypesIndex
     *
     * .
     *
     */
    public function testPartnersBusinessunitsTypesIndex()
    {

    }

    /**
     * Test case for partnersBusinessunitsTypesUpdate
     *
     * .
     *
     */
    public function testPartnersBusinessunitsTypesUpdate()
    {

    }

    /**
     * Test case for partnersBusinessunitsUpdate
     *
     * .
     *
     */
    public function testPartnersBusinessunitsUpdate()
    {

    }

    /**
     * Test case for partnersCategoriesIndex
     *
     * .
     *
     */
    public function testPartnersCategoriesIndex()
    {

    }

    /**
     * Test case for partnersCertificationsCreate
     *
     * .
     *
     */
    public function testPartnersCertificationsCreate()
    {

    }

    /**
     * Test case for partnersCertificationsDelete
     *
     * .
     *
     */
    public function testPartnersCertificationsDelete()
    {

    }

    /**
     * Test case for partnersCertificationsGet
     *
     * .
     *
     */
    public function testPartnersCertificationsGet()
    {

    }

    /**
     * Test case for partnersCertificationsIndex
     *
     * .
     *
     */
    public function testPartnersCertificationsIndex()
    {

    }

    /**
     * Test case for partnersCertificationsUpdate
     *
     * .
     *
     */
    public function testPartnersCertificationsUpdate()
    {

    }

    /**
     * Test case for partnersContentsDelete
     *
     * .
     *
     */
    public function testPartnersContentsDelete()
    {

    }

    /**
     * Test case for partnersContentsGet
     *
     * .
     *
     */
    public function testPartnersContentsGet()
    {

    }

    /**
     * Test case for partnersContentsUpdate
     *
     * .
     *
     */
    public function testPartnersContentsUpdate()
    {

    }

    /**
     * Test case for partnersContractoffergroupsCreate
     *
     * .
     *
     */
    public function testPartnersContractoffergroupsCreate()
    {

    }

    /**
     * Test case for partnersContractoffergroupsIndex
     *
     * .
     *
     */
    public function testPartnersContractoffergroupsIndex()
    {

    }

    /**
     * Test case for partnersContractsActionsCreate
     *
     * .
     *
     */
    public function testPartnersContractsActionsCreate()
    {

    }

    /**
     * Test case for partnersContractsAllocationpausesDelete
     *
     * .
     *
     */
    public function testPartnersContractsAllocationpausesDelete()
    {

    }

    /**
     * Test case for partnersContractsAllocationpausesUpdate
     *
     * .
     *
     */
    public function testPartnersContractsAllocationpausesUpdate()
    {

    }

    /**
     * Test case for partnersContractsCreate
     *
     * .
     *
     */
    public function testPartnersContractsCreate()
    {

    }

    /**
     * Test case for partnersContractsDelete
     *
     * .
     *
     */
    public function testPartnersContractsDelete()
    {

    }

    /**
     * Test case for partnersContractsGet
     *
     * .
     *
     */
    public function testPartnersContractsGet()
    {

    }

    /**
     * Test case for partnersContractsIndex
     *
     * .
     *
     */
    public function testPartnersContractsIndex()
    {

    }

    /**
     * Test case for partnersContractsPdfGet
     *
     * .
     *
     */
    public function testPartnersContractsPdfGet()
    {

    }

    /**
     * Test case for partnersContractsSignedpdfCreate
     *
     * .
     *
     */
    public function testPartnersContractsSignedpdfCreate()
    {

    }

    /**
     * Test case for partnersContractsSignedpdfGet
     *
     * .
     *
     */
    public function testPartnersContractsSignedpdfGet()
    {

    }

    /**
     * Test case for partnersContractsSigningurlGet
     *
     * .
     *
     */
    public function testPartnersContractsSigningurlGet()
    {

    }

    /**
     * Test case for partnersContractsUpdate
     *
     * .
     *
     */
    public function testPartnersContractsUpdate()
    {

    }

    /**
     * Test case for partnersCouponsActionsCreate
     *
     * .
     *
     */
    public function testPartnersCouponsActionsCreate()
    {

    }

    /**
     * Test case for partnersCouponsCreate
     *
     * .
     *
     */
    public function testPartnersCouponsCreate()
    {

    }

    /**
     * Test case for partnersCouponsIndex
     *
     * .
     *
     */
    public function testPartnersCouponsIndex()
    {

    }

    /**
     * Test case for partnersCreate
     *
     * Create a Partner.
     *
     */
    public function testPartnersCreate()
    {

    }

    /**
     * Test case for partnersDelete
     *
     * .
     *
     */
    public function testPartnersDelete()
    {

    }

    /**
     * Test case for partnersDeliverablesCreate
     *
     * .
     *
     */
    public function testPartnersDeliverablesCreate()
    {

    }

    /**
     * Test case for partnersDeliverablesCreate_0
     *
     * .
     *
     */
    public function testPartnersDeliverablesCreate0()
    {

    }

    /**
     * Test case for partnersDeliverablesGet
     *
     * .
     *
     */
    public function testPartnersDeliverablesGet()
    {

    }

    /**
     * Test case for partnersDeliverablesGet_0
     *
     * .
     *
     */
    public function testPartnersDeliverablesGet0()
    {

    }

    /**
     * Test case for partnersDeliverablesIndex
     *
     * .
     *
     */
    public function testPartnersDeliverablesIndex()
    {

    }

    /**
     * Test case for partnersDeliverablesIndex_0
     *
     * .
     *
     */
    public function testPartnersDeliverablesIndex0()
    {

    }

    /**
     * Test case for partnersDeliverablesLinesCreate
     *
     * .
     *
     */
    public function testPartnersDeliverablesLinesCreate()
    {

    }

    /**
     * Test case for partnersDeliverablesLinesCreate_0
     *
     * .
     *
     */
    public function testPartnersDeliverablesLinesCreate0()
    {

    }

    /**
     * Test case for partnersDeliverablesLinesDelete
     *
     * .
     *
     */
    public function testPartnersDeliverablesLinesDelete()
    {

    }

    /**
     * Test case for partnersDeliverablesLinesDelete_0
     *
     * .
     *
     */
    public function testPartnersDeliverablesLinesDelete0()
    {

    }

    /**
     * Test case for partnersDeliverablesLinesGet
     *
     * .
     *
     */
    public function testPartnersDeliverablesLinesGet()
    {

    }

    /**
     * Test case for partnersDeliverablesLinesGet_0
     *
     * .
     *
     */
    public function testPartnersDeliverablesLinesGet0()
    {

    }

    /**
     * Test case for partnersDeliverablesLinesIndex
     *
     * .
     *
     */
    public function testPartnersDeliverablesLinesIndex()
    {

    }

    /**
     * Test case for partnersDeliverablesLinesIndex_0
     *
     * .
     *
     */
    public function testPartnersDeliverablesLinesIndex0()
    {

    }

    /**
     * Test case for partnersDeliverablesLinesUpdate
     *
     * .
     *
     */
    public function testPartnersDeliverablesLinesUpdate()
    {

    }

    /**
     * Test case for partnersDeliverablesLinesUpdate_0
     *
     * .
     *
     */
    public function testPartnersDeliverablesLinesUpdate0()
    {

    }

    /**
     * Test case for partnersDeliverablesUpdate
     *
     * .
     *
     */
    public function testPartnersDeliverablesUpdate()
    {

    }

    /**
     * Test case for partnersDeliverablesUpdate_0
     *
     * .
     *
     */
    public function testPartnersDeliverablesUpdate0()
    {

    }

    /**
     * Test case for partnersDiscountsCreate
     *
     * .
     *
     */
    public function testPartnersDiscountsCreate()
    {

    }

    /**
     * Test case for partnersDiscountsDelete
     *
     * .
     *
     */
    public function testPartnersDiscountsDelete()
    {

    }

    /**
     * Test case for partnersDiscountsIndex
     *
     * .
     *
     */
    public function testPartnersDiscountsIndex()
    {

    }

    /**
     * Test case for partnersEmployeenotesCreate
     *
     * .
     *
     */
    public function testPartnersEmployeenotesCreate()
    {

    }

    /**
     * Test case for partnersEmployeenotesDelete
     *
     * .
     *
     */
    public function testPartnersEmployeenotesDelete()
    {

    }

    /**
     * Test case for partnersEmployeenotesIndex
     *
     * .
     *
     */
    public function testPartnersEmployeenotesIndex()
    {

    }

    /**
     * Test case for partnersFeaturesCreate
     *
     * .
     *
     */
    public function testPartnersFeaturesCreate()
    {

    }

    /**
     * Test case for partnersFeaturesDelete
     *
     * .
     *
     */
    public function testPartnersFeaturesDelete()
    {

    }

    /**
     * Test case for partnersFeesCreate
     *
     * .
     *
     */
    public function testPartnersFeesCreate()
    {

    }

    /**
     * Test case for partnersFeesDelete
     *
     * .
     *
     */
    public function testPartnersFeesDelete()
    {

    }

    /**
     * Test case for partnersFeesIndex
     *
     * .
     *
     */
    public function testPartnersFeesIndex()
    {

    }

    /**
     * Test case for partnersGet
     *
     * Get a single partner by ID.
     *
     */
    public function testPartnersGet()
    {

    }

    /**
     * Test case for partnersImpressumsCreate
     *
     * .
     *
     */
    public function testPartnersImpressumsCreate()
    {

    }

    /**
     * Test case for partnersIndex
     *
     * List partners.
     *
     */
    public function testPartnersIndex()
    {

    }

    /**
     * Test case for partnersIndustriesCreate
     *
     * .
     *
     */
    public function testPartnersIndustriesCreate()
    {

    }

    /**
     * Test case for partnersIndustriesDelete
     *
     * .
     *
     */
    public function testPartnersIndustriesDelete()
    {

    }

    /**
     * Test case for partnersIndustriesGet
     *
     * .
     *
     */
    public function testPartnersIndustriesGet()
    {

    }

    /**
     * Test case for partnersIndustriesIndex
     *
     * .
     *
     */
    public function testPartnersIndustriesIndex()
    {

    }

    /**
     * Test case for partnersIndustriesUpdate
     *
     * .
     *
     */
    public function testPartnersIndustriesUpdate()
    {

    }

    /**
     * Test case for partnersInvoicingsIndex
     *
     * .
     *
     */
    public function testPartnersInvoicingsIndex()
    {

    }

    /**
     * Test case for partnersInvoicingsIndex_0
     *
     * .
     *
     */
    public function testPartnersInvoicingsIndex0()
    {

    }

    /**
     * Test case for partnersLeadtypesCreate
     *
     * .
     *
     */
    public function testPartnersLeadtypesCreate()
    {

    }

    /**
     * Test case for partnersLeadtypesDelete
     *
     * .
     *
     */
    public function testPartnersLeadtypesDelete()
    {

    }

    /**
     * Test case for partnersLeadtypesGet
     *
     * .
     *
     */
    public function testPartnersLeadtypesGet()
    {

    }

    /**
     * Test case for partnersLeadtypesGet_0
     *
     * .
     *
     */
    public function testPartnersLeadtypesGet0()
    {

    }

    /**
     * Test case for partnersLeadtypesIndex
     *
     * .
     *
     */
    public function testPartnersLeadtypesIndex()
    {

    }

    /**
     * Test case for partnersLeadtypesIndex_0
     *
     * .
     *
     */
    public function testPartnersLeadtypesIndex0()
    {

    }

    /**
     * Test case for partnersLeadtypesUpdate
     *
     * .
     *
     */
    public function testPartnersLeadtypesUpdate()
    {

    }

    /**
     * Test case for partnersNotesCreate
     *
     * .
     *
     */
    public function testPartnersNotesCreate()
    {

    }

    /**
     * Test case for partnersNotesCreate_0
     *
     * .
     *
     */
    public function testPartnersNotesCreate0()
    {

    }

    /**
     * Test case for partnersNotesGet
     *
     * .
     *
     */
    public function testPartnersNotesGet()
    {

    }

    /**
     * Test case for partnersNotesIndex
     *
     * .
     *
     */
    public function testPartnersNotesIndex()
    {

    }

    /**
     * Test case for partnersNotesIndex_0
     *
     * .
     *
     */
    public function testPartnersNotesIndex0()
    {

    }

    /**
     * Test case for partnersQuoteloanproductpricesCreate
     *
     * .
     *
     */
    public function testPartnersQuoteloanproductpricesCreate()
    {

    }

    /**
     * Test case for partnersQuoteloanproductpricesDelete
     *
     * .
     *
     */
    public function testPartnersQuoteloanproductpricesDelete()
    {

    }

    /**
     * Test case for partnersQuoteloanproductpricesIndex
     *
     * .
     *
     */
    public function testPartnersQuoteloanproductpricesIndex()
    {

    }

    /**
     * Test case for partnersQuoteproductcommentsCreate
     *
     * .
     *
     */
    public function testPartnersQuoteproductcommentsCreate()
    {

    }

    /**
     * Test case for partnersQuoteproductcommentsDelete
     *
     * .
     *
     */
    public function testPartnersQuoteproductcommentsDelete()
    {

    }

    /**
     * Test case for partnersQuoteproductcommentsIndex
     *
     * .
     *
     */
    public function testPartnersQuoteproductcommentsIndex()
    {

    }

    /**
     * Test case for partnersQuoteproductpricesCreate
     *
     * .
     *
     */
    public function testPartnersQuoteproductpricesCreate()
    {

    }

    /**
     * Test case for partnersQuoteproductpricesDelete
     *
     * .
     *
     */
    public function testPartnersQuoteproductpricesDelete()
    {

    }

    /**
     * Test case for partnersQuoteproductpricesIndex
     *
     * .
     *
     */
    public function testPartnersQuoteproductpricesIndex()
    {

    }

    /**
     * Test case for partnersQuotevendorsIndex
     *
     * .
     *
     */
    public function testPartnersQuotevendorsIndex()
    {

    }

    /**
     * Test case for partnersRevenuerangesCreate
     *
     * .
     *
     */
    public function testPartnersRevenuerangesCreate()
    {

    }

    /**
     * Test case for partnersRevenuesegmentsCreate
     *
     * .
     *
     */
    public function testPartnersRevenuesegmentsCreate()
    {

    }

    /**
     * Test case for partnersRevenuesegmentsCreate_0
     *
     * .
     *
     */
    public function testPartnersRevenuesegmentsCreate0()
    {

    }

    /**
     * Test case for partnersRevenuesegmentsDelete
     *
     * .
     *
     */
    public function testPartnersRevenuesegmentsDelete()
    {

    }

    /**
     * Test case for partnersRevenuesegmentsIndex
     *
     * .
     *
     */
    public function testPartnersRevenuesegmentsIndex()
    {

    }

    /**
     * Test case for partnersSectorsIndex
     *
     * .
     *
     */
    public function testPartnersSectorsIndex()
    {

    }

    /**
     * Test case for partnersSectorsUpdate
     *
     * .
     *
     */
    public function testPartnersSectorsUpdate()
    {

    }

    /**
     * Test case for partnersSellingpointsCreate
     *
     * .
     *
     */
    public function testPartnersSellingpointsCreate()
    {

    }

    /**
     * Test case for partnersSellingpointsDelete
     *
     * .
     *
     */
    public function testPartnersSellingpointsDelete()
    {

    }

    /**
     * Test case for partnersSellingpointsIndex
     *
     * .
     *
     */
    public function testPartnersSellingpointsIndex()
    {

    }

    /**
     * Test case for partnersSellingpointsUpdate
     *
     * .
     *
     */
    public function testPartnersSellingpointsUpdate()
    {

    }

    /**
     * Test case for partnersSubscriptionagreementsActionsCreate
     *
     * .
     *
     */
    public function testPartnersSubscriptionagreementsActionsCreate()
    {

    }

    /**
     * Test case for partnersSubscriptionagreementsCreate
     *
     * .
     *
     */
    public function testPartnersSubscriptionagreementsCreate()
    {

    }

    /**
     * Test case for partnersSubscriptionagreementsIndex
     *
     * .
     *
     */
    public function testPartnersSubscriptionagreementsIndex()
    {

    }

    /**
     * Test case for partnersSubscriptionagreementsUpdate
     *
     * .
     *
     */
    public function testPartnersSubscriptionagreementsUpdate()
    {

    }

    /**
     * Test case for partnersSubscriptionsActionsCreate
     *
     * .
     *
     */
    public function testPartnersSubscriptionsActionsCreate()
    {

    }

    /**
     * Test case for partnersSubscriptionsCreate
     *
     * .
     *
     */
    public function testPartnersSubscriptionsCreate()
    {

    }

    /**
     * Test case for partnersSubscriptionsIndex
     *
     * .
     *
     */
    public function testPartnersSubscriptionsIndex()
    {

    }

    /**
     * Test case for partnersSubscriptionsPausesCreate
     *
     * .
     *
     */
    public function testPartnersSubscriptionsPausesCreate()
    {

    }

    /**
     * Test case for partnersSubscriptionsPausesDelete
     *
     * .
     *
     */
    public function testPartnersSubscriptionsPausesDelete()
    {

    }

    /**
     * Test case for partnersSubscriptionsPausesIndex
     *
     * .
     *
     */
    public function testPartnersSubscriptionsPausesIndex()
    {

    }

    /**
     * Test case for partnersSubscriptionsPricesCreate
     *
     * .
     *
     */
    public function testPartnersSubscriptionsPricesCreate()
    {

    }

    /**
     * Test case for partnersSubscriptionsPricesDelete
     *
     * .
     *
     */
    public function testPartnersSubscriptionsPricesDelete()
    {

    }

    /**
     * Test case for partnersSubscriptionsPricesIndex
     *
     * .
     *
     */
    public function testPartnersSubscriptionsPricesIndex()
    {

    }

    /**
     * Test case for partnersSubscriptionsUpdate
     *
     * .
     *
     */
    public function testPartnersSubscriptionsUpdate()
    {

    }

    /**
     * Test case for partnersSubscriptiontypesIndex
     *
     * .
     *
     */
    public function testPartnersSubscriptiontypesIndex()
    {

    }

    /**
     * Test case for partnersSubscriptiontypesIndex_0
     *
     * .
     *
     */
    public function testPartnersSubscriptiontypesIndex0()
    {

    }

    /**
     * Test case for partnersSuggestIndex
     *
     * .
     *
     */
    public function testPartnersSuggestIndex()
    {

    }

    /**
     * Test case for partnersTitlesIndex
     *
     * .
     *
     */
    public function testPartnersTitlesIndex()
    {

    }

    /**
     * Test case for partnersTransactionsIndex
     *
     * .
     *
     */
    public function testPartnersTransactionsIndex()
    {

    }

    /**
     * Test case for partnersUpdate
     *
     * .
     *
     */
    public function testPartnersUpdate()
    {

    }

    /**
     * Test case for partnersUsersActionsCreate
     *
     * .
     *
     */
    public function testPartnersUsersActionsCreate()
    {

    }

    /**
     * Test case for partnersUsersContentsDelete
     *
     * .
     *
     */
    public function testPartnersUsersContentsDelete()
    {

    }

    /**
     * Test case for partnersUsersContentsDelete_0
     *
     * .
     *
     */
    public function testPartnersUsersContentsDelete0()
    {

    }

    /**
     * Test case for partnersUsersContentsGet
     *
     * .
     *
     */
    public function testPartnersUsersContentsGet()
    {

    }

    /**
     * Test case for partnersUsersContentsGet_0
     *
     * .
     *
     */
    public function testPartnersUsersContentsGet0()
    {

    }

    /**
     * Test case for partnersUsersContentsUpdate
     *
     * .
     *
     */
    public function testPartnersUsersContentsUpdate()
    {

    }

    /**
     * Test case for partnersUsersContentsUpdate_0
     *
     * .
     *
     */
    public function testPartnersUsersContentsUpdate0()
    {

    }

    /**
     * Test case for partnersUsersCreate
     *
     * .
     *
     */
    public function testPartnersUsersCreate()
    {

    }

    /**
     * Test case for partnersUsersCreate_0
     *
     * .
     *
     */
    public function testPartnersUsersCreate0()
    {

    }

    /**
     * Test case for partnersUsersDelete
     *
     * .
     *
     */
    public function testPartnersUsersDelete()
    {

    }

    /**
     * Test case for partnersUsersGet
     *
     * .
     *
     */
    public function testPartnersUsersGet()
    {

    }

    /**
     * Test case for partnersUsersGet_0
     *
     * .
     *
     */
    public function testPartnersUsersGet0()
    {

    }

    /**
     * Test case for partnersUsersIndex
     *
     * .
     *
     */
    public function testPartnersUsersIndex()
    {

    }

    /**
     * Test case for partnersUsersIndex_0
     *
     * .
     *
     */
    public function testPartnersUsersIndex0()
    {

    }

    /**
     * Test case for partnersUsersUpdate
     *
     * .
     *
     */
    public function testPartnersUsersUpdate()
    {

    }

    /**
     * Test case for partnersUsersUpdate_0
     *
     * .
     *
     */
    public function testPartnersUsersUpdate0()
    {

    }

    /**
     * Test case for partnersVerificationsIndex
     *
     * .
     *
     */
    public function testPartnersVerificationsIndex()
    {

    }

    /**
     * Test case for partnersVerificationsIndex_0
     *
     * .
     *
     */
    public function testPartnersVerificationsIndex0()
    {

    }

    /**
     * Test case for partnersVerificationsUpdate
     *
     * .
     *
     */
    public function testPartnersVerificationsUpdate()
    {

    }

}
