<?php
/**
 * ProjectsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Ageras\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ageras.com API
 *
 * this is the Ageras API
 *
 * OpenAPI spec version: 2.0
 * Contact: cto@ageras.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Ageras\Api;

use \Ageras\Api\Configuration;
use \Ageras\Api\ApiClient;
use \Ageras\Api\ApiException;
use \Ageras\Api\ObjectSerializer;

/**
 * ProjectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ageras\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for projectsCreate
     *
     * .
     *
     */
    public function testProjectsCreate()
    {

    }

    /**
     * Test case for projectsDelete
     *
     * .
     *
     */
    public function testProjectsDelete()
    {

    }

    /**
     * Test case for projectsEventsCreate
     *
     * .
     *
     */
    public function testProjectsEventsCreate()
    {

    }

    /**
     * Test case for projectsEventsCreate_0
     *
     * .
     *
     */
    public function testProjectsEventsCreate0()
    {

    }

    /**
     * Test case for projectsEventsDelete
     *
     * .
     *
     */
    public function testProjectsEventsDelete()
    {

    }

    /**
     * Test case for projectsEventsGet
     *
     * .
     *
     */
    public function testProjectsEventsGet()
    {

    }

    /**
     * Test case for projectsEventsGet_0
     *
     * .
     *
     */
    public function testProjectsEventsGet0()
    {

    }

    /**
     * Test case for projectsEventsIndex
     *
     * .
     *
     */
    public function testProjectsEventsIndex()
    {

    }

    /**
     * Test case for projectsEventsIndex_0
     *
     * .
     *
     */
    public function testProjectsEventsIndex0()
    {

    }

    /**
     * Test case for projectsEventsUpdate
     *
     * .
     *
     */
    public function testProjectsEventsUpdate()
    {

    }

    /**
     * Test case for projectsEventsUpdate_0
     *
     * .
     *
     */
    public function testProjectsEventsUpdate0()
    {

    }

    /**
     * Test case for projectsGet
     *
     * .
     *
     */
    public function testProjectsGet()
    {

    }

    /**
     * Test case for projectsIndex
     *
     * .
     *
     */
    public function testProjectsIndex()
    {

    }

    /**
     * Test case for projectsNotesCreate
     *
     * .
     *
     */
    public function testProjectsNotesCreate()
    {

    }

    /**
     * Test case for projectsNotesCreate_0
     *
     * .
     *
     */
    public function testProjectsNotesCreate0()
    {

    }

    /**
     * Test case for projectsNotesDelete
     *
     * .
     *
     */
    public function testProjectsNotesDelete()
    {

    }

    /**
     * Test case for projectsNotesGet
     *
     * .
     *
     */
    public function testProjectsNotesGet()
    {

    }

    /**
     * Test case for projectsNotesGet_0
     *
     * .
     *
     */
    public function testProjectsNotesGet0()
    {

    }

    /**
     * Test case for projectsNotesIndex
     *
     * .
     *
     */
    public function testProjectsNotesIndex()
    {

    }

    /**
     * Test case for projectsNotesIndex_0
     *
     * .
     *
     */
    public function testProjectsNotesIndex0()
    {

    }

    /**
     * Test case for projectsNotesUpdate
     *
     * .
     *
     */
    public function testProjectsNotesUpdate()
    {

    }

    /**
     * Test case for projectsNotesUpdate_0
     *
     * .
     *
     */
    public function testProjectsNotesUpdate0()
    {

    }

    /**
     * Test case for projectsStatusesGet
     *
     * .
     *
     */
    public function testProjectsStatusesGet()
    {

    }

    /**
     * Test case for projectsStatusesIndex
     *
     * .
     *
     */
    public function testProjectsStatusesIndex()
    {

    }

    /**
     * Test case for projectsUpdate
     *
     * .
     *
     */
    public function testProjectsUpdate()
    {

    }

}
